#!/bin/bash

echo "Päivitetty" > /var/log/paivitysloki
date >> /var/log/paivitysloki
echo "Päivitetään!"
sudo apt-get update >> /var/log/paivitysloki  2>&1
sudo apt-get upgrade -y >> /var/log/paivitysloki 2>&1
echo "Poistetaan vanhoja tietoja"
sudo apt-get autoremove -y >> /var/log/paivitysloki 2>&1
sudo apt-get clean -y >> /var/log/paivitysloki 2>&1
echo "Valmis!"
echo "Valmis!" >> /var/log/paivitysloki
echo "Käynnistetään uudestaan"
sleep 5
sudo reboot
