#!/bin/bash

echo "Päivitetty" > /home/anders/Documents/paivitysloki
date >> /home/anders/Documents/paivitysloki
echo "Päivitetään!"
sudo apt-get update >> /home/anders/Documents/paivitysloki  2>&1
sudo apt-get upgrade -y >> /home/anders/Documents/paivitysloki 2>&1
echo "Poistetaan vanhoja tietoja"
sudo apt-get autoremove -y >> /home/anders/Documents/paivitysloki 2>&1
sudo apt-get clean -y >> /home/anders/Documents/paivitysloki 2>&1
echo "Valmis!"
echo "Valmis!" >> /home/anders/Documents/paivitysloki
echo "Käynnistetään uudestaan"
sudo reboot
